terminate called after throwing an instance of 'std::runtime_error'
  what():  could not open /home/surya/assignment/OWN/surya/training1/work/fcvtv/fcvtv.elf (did you misspell it? If VCS, did you forget +permissive/+permissive-off?)
